In [1]:
import numpy as np
%load_ext Cython


In [561]:
a = np.random.rand(6)

In [562]:
np.sort(a)

array([0.02986917, 0.12936271, 0.20880785, 0.21672667, 0.8883051 ,
       0.98590451])

In [209]:
def merge(A, p, q, r):
    n1 = q-p+1
    n2 = r-q
    L = [100000 for i in range(0, n1+2)]
    R = [100000 for i in range(0, n2+2)]
    for i in range(1, n1+1):
        L[i] = A[p+i-1]
    for j in range(1, n2+1):
        R[j] = A[q+j]
    i = 1
    j = 1
    for k in range(p, r+1):
        if L[i] <= R[j]:
            A[k] = L[i]
            i += 1
        else:
            A[k] = R[j]
            j += 1
        
def merge_sort(A, p, r):
    if p < r:
        q = (p+r)//2
        merge_sort(A, p, q)
        merge_sort(A, q+1, r)
        merge(A, p, q, r)

In [50]:
n = 6
a = np.random.rand(n+1)
a[0] = 0
merge_sort(a, 1, n)
print(a)

[0.         0.26052275 0.2614643  0.2898512  0.38388131 0.63454103
 0.89888392]


In [1070]:
def p_scan_up(x, t, i, j):
    if i == j:
        return x[i]
    k = (i+j)//2
    t[k] = p_scan_up(x, t, i, k)
    right = p_scan_up(x, t, k+1, j)
    return t[k] + right
def p_scan_down(v, x, t, y, i, j):
    if i == j:
        y[i] = v + x[i]
    else:
        k = (i+j)//2
        p_scan_down(v, x, t, y, i, k)
        p_scan_down(t[k]+v, x, t, y, k+1, j)
def p_scan_3(x):
    n = len(x)
    y = [-1 for i in range(n)]
    t = [-1 for i in range(n)]
    y[0] = x[0]
    if n > 1:
        p_scan_up(x, t, 0, n-1)
        p_scan_down(0, x, t, y, 0, n-1)
    print(t)
    return y

In [577]:
n = 6
a = np.random.rand(n)
a = [1, 2, 3, 4, 5, 6]
a = [0, 1, 2, 3, 4]
p_scan_3(a)

[0, 1, 3, 3, -1]


[0, 1, 3, 6, 10]

In [1069]:
def p_scan_up(x, y, i, j):
    n = j -i + 1
    for k in range(i, j+1):
        y[k] = 0
    lgn = int(np.log2(n))
    for k in range(lgn):
        _2k = 2**k
        _2k1 = 2**(k+1)                  
        for p in range(i, j+1):
            if (p+1) % _2k1 == 0:
                y[p] = x[p]
        #print("k=%d"%k)
        for p in range(i, j+1):
            if (p+1) % _2k1 == 0:
                y[p] = x[p] + y[p-_2k]

def p_scan_down(x, t, y, i, j):
    n = j - i + 1
    lgn = int(np.log2(n))
    for k in range(i, j):
        y[k] = 0
    y[j] = 0
    for k in reversed(range(lgn)):
        print("k=%d"%k)
        _2k = 2**k
        _2k1 = 2**(k+1)                             
        for p in range(i, j+1):   
            if (p+1) % _2k1 == 0:
                print(p-_2k1+1)
                print(y)
                tmp = y[p]
                y[p] = t[p-_2k] + t[p-_2k1+1] + y[p-_2k+1]
                y[p-_2k] = tmp
                print(t)
                print(y)
                print('****')
            
def p_scan_3(x):
    n = len(x)
    y = [0 for i in range(n)]
    t = [0 for i in range(n)]
    if n > 1:
        p_scan_up(x, t, 0, n-1)
        print(t)
        #p_scan_down(x, t, y, 0, n-1)
    return np.array(y)

In [559]:
n = 6
a = np.random.rand(n)
a = [0, 1, 2, 3, 4, 5]
p_scan_3(a)

[0, 1, 0, 4, 0, 5]


array([0, 0, 0, 0, 0, 0])

In [549]:
print(list(np.arange(np.log(6)/np.log(2))))

[0.0, 1.0, 2.0]


In [430]:
for k in reversed(range(3-1)):
    print(k)

1
0


In [368]:
print(list(range(int(np.log(6)/np.log(2)))))

[0, 1]


In [451]:
for i in range(2, 0, -1):
    print(i)

2
1


In [452]:
int(np.log(5)/np.log(2))

2

In [191]:
a = [(0, 6)]
count = 1
while (len(a) > 0):
    i, j = a.pop()
    if i == j:
        continue
    k = (i+j)//2
    print(count, i, j, k)
    a.append((i, k))
    a.append((k+1, j))
    count += 1

1 0 6 3
2 4 6 5
3 4 5 4
4 0 3 1
5 2 3 2
6 0 1 0


In [190]:
np.log(6)/np.log(2)

2.584962500721156

In [201]:
def sum_array_main_loop(a, b, c, i, j):
    if i == j:
        c[i] = a[i] + b[i]
    else:
        k = (i+j)//2
        sum_array_main_loop(a, b, c, i, k)
        sum_array_main_loop(a, b, c, k+1, j)

In [202]:
n = 6
a = np.random.rand(n)
b = np.random.rand(n)
c = np.zeros_like(a)
sum_array_main_loop(a, b, c, 0, n-1)

In [204]:
c == (a+b)

array([ True,  True,  True,  True,  True,  True])

In [629]:
def f(x, y):
    return x+y

In [669]:
def run_in_parallel(f, args, p, r):
    a = list(range(p, r+1))
    np.random.shuffle(a)
    print(a)
    for i in a:
        f(i, *args)

In [670]:
def f(i, x):
    x[i] = x[i-1]*i

In [683]:
x = [2, 3, 5, 9]
run_in_parallel(f, (x,), 1, len(x)-1)

[3, 2, 1]


In [684]:
x

[2, 2, 6, 15]

In [ ]:
def prefix_sum(elements):
    n = len(elements)
    p = 4
    prefix_sum = [0 for _ in elements]
    

In [1335]:
x = [1, 2, 3, 4, 5]#, 6, 7, 8, 9, 10, 11]
x = np.random.rand(25)
n = len(x)
d = int(np.log2(n)-.001)
_2n1 = 2**(d+1)-1
print(n, d, _2n1)
indices = [0 for _ in range(_2n1)]
_j = [0 for _ in range(_2n1)]
_s = np.array([0 for _ in range(_2n1)])
_out = [0 for _ in range(_2n1)]
indices[0] = 0
_j[0] = n-1
_s[0] = 1
t = [0 for _ in x]
for d in range(0, d+1):
    #print(_s)
    _s_old = _s.copy()
    for p in range(_2n1):
        i = indices[p]
        j = _j[p]
        if _s_old[p] == 1:
            #if j - i <= 1:
            #    _out[p] = np.sum(x[i:j+1])
            if j - i == 0:
                _out[p] = x[i]
            elif j == i+1:
                _out[p] = x[i] + x[j]
                t[i] = x[i]           
            #if i == j:
            #    _out[p] = x[i]
            #elif j == i+1:
            #    _out[p] = x[i] + x[j]
            else:
                k = (indices[p] + _j[p])//2
                #print(i, j, k)
                p_left = p*2+1
                p_right = p*2+2
                #print(p, p_left, p_right)
                indices[p_right] = k+1
                _j[p_right] = j
                _s[p_right] = 1
                indices[p_left] = i
                _j[p_left] = k
                _s[p_left] = 1
                _s[p] = 0
print(_s)
print(_out)
print("***********")
#for d in range(0, d+1):
#    _s_old = _s.copy()
#    for p in range(1, _2n1):
#        i = indices[p]
#        j = _j[p]
#        if _s_old[p] == 1:   
#            parent = ((p+1) // 2) - 1
#            _out[parent] += _out[p]
#            _s[parent] = 1
#            _s[p] = 0
#            _out[p] = 0
#print(_s)
for d in range(0, d+1):
    _s_old = _s.copy()
    for p in range(1, _2n1):
        i = indices[p]
        j = _j[p]
        if _s_old[p] == 1 and p%2==1:
            parent = (p-1) // 2
            k = (indices[parent] + _j[parent])//2
            if p %2 == 1:
                t[k] += _out[p]
            _out[parent] += _out[p] + _out[p+1]
            _s[parent] = 1
            _s[p] = 0
#print(_s)

25 4 31
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.8005165380196756, 1.1127847653050338, 0.5443179107981454, 0.5413244589402582, 0.6472324119040235, 0.4622568443545666, 1.0551842745488509, 0.3531378128146594, 1.0774335674007385, 0.047675887686255414, 1.8342667462982072, 0.36994188868264855, 1.1946854571180205, 0.9946746213650465, 1.4804438225636571, 0.3848725236329388]
***********


In [1336]:
def print_with_shit(x):
    for i in x:
        print("%-3d"%i, end='')
    print()

In [1337]:
_out

[12.900749531432727,
 5.516755016685213,
 7.383994514747513,
 2.998943673063113,
 2.5178113436221006,
 3.32931809006785,
 4.054676424679663,
 1.9133013033247095,
 1.0856423697384034,
 1.10948925625859,
 1.4083220873635103,
 1.125109455086994,
 2.204208634980856,
 2.189360078483067,
 1.8653163461965958,
 0.8005165380196756,
 1.1127847653050338,
 0.5443179107981454,
 0.5413244589402582,
 0.6472324119040235,
 0.4622568443545666,
 1.0551842745488509,
 0.3531378128146594,
 1.0774335674007385,
 0.047675887686255414,
 1.8342667462982072,
 0.36994188868264855,
 1.1946854571180205,
 0.9946746213650465,
 1.4804438225636571,
 0.3848725236329388]

In [1331]:
print(sum(x))

9.914997696208628


In [1332]:
print(t)

[0.026346048365082364, 1.1240949312306616, 0.026346048365082364, 1.2977250628862484, 0.026346048365082364, 1.8662399897746478, 3.5208255639253414, 0.026346048365082364, 1.0403504133524046, 1.056397351036968, 0.026346048365082364, 0.2107202649940968, 5.21710713267408, 0.026346048365082364, 0.9672093651028647, 1.101151170568237, 0.026346048365082364, 0.8400300965305804, 2.009013691774762, 0.026346048365082364, 0.775647012356247, 1.7192450214943986, 0.026346048365082364, 1.048669995360632, 0.026346048365082364]


In [1333]:
t1 = [0 for _ in x]
p_scan_up(x, t1, 0, n-1)

9.914997696208626

In [1334]:
np.array(t)-t1

array([-0.6557372 ,  0.02634605, -0.05912776,  0.02634605, -0.96607864,
        0.02634605,  0.02634605, -0.75046097,  0.02634605,  0.02634605,
       -0.12552176,  0.02634605,  0.02634605, -0.48667387,  0.02634605,
        0.02634605, -0.60940289,  0.02634605,  0.02634605, -0.60082966,
        0.02634605,  0.02634605, -0.02452553,  0.02634605,  0.02634605])

In [1264]:
t1

[0.25859541504396777,
 0.7876455612609209,
 0.283208968318428,
 1.1333017123057416,
 0.8120025351242497,
 0.8714664307779979,
 2.352711129003508,
 0.7950427947979659,
 0.9468639604176441,
 1.703514959222105,
 0.022987123248266683,
 0.8789026682829436,
 5.685701530984562,
 0.5558649454996404,
 1.4459615768027507,
 1.945379778936781,
 0.48445489960455823,
 1.2027132152229825,
 3.2618458615093298,
 0.5637244377667862,
 1.5497694783759726,
 1.6873859659967183,
 0.9299489766247147,
 1.5030824505440923,
 0]

In [1103]:
x = [1, 2, 3, 4, 5]#, 6, 7, 8, 9, 10, 11]
x = np.random.rand(16)
n = len(x)
d = int(np.log2(n))+1
_2n1 = 2**(d+1)-1
print(n, d, _2n1)
indices = [0 for _ in range(_2n1)]
_j = [0 for _ in range(_2n1)]
_s = np.array([0 for _ in range(_2n1)])
_out = [0 for _ in range(_2n1)]
indices[0] = 0
_j[0] = n-1
_s[0] = 1
for d in range(0, d+1):
    #print(_s)
    _s_old = _s.copy()
    for p in range(_2n1):
        i = indices[p]
        j = _j[p]
        if _s_old[p] == 1:
            if i == j:
                _out[p] = x[i]
            else:
                k = (indices[p] + _j[p])//2
                #print(i, j, k)
                p_left = p*2+1
                p_right = p*2+2
                #print(p, p_left, p_right)
                indices[p_right] = k+1
                _j[p_right] = j
                _s[p_right] = 1
                indices[p_left] = i
                _j[p_left] = k
                _s[p_left] = 1
                _s[p] = 0
print(_s)
print(_out)
print("***********")
#for d in range(0, d+1):
#    _s_old = _s.copy()
#    for p in range(1, _2n1):
#        i = indices[p]
#        j = _j[p]
#        if _s_old[p] == 1:   
#            parent = ((p+1) // 2) - 1
#            _out[parent] += _out[p]
#            _s[parent] = 1
#            _s[p] = 0
#            _out[p] = 0
#print(_s)
t = [0 for _ in x]
for d in range(0, d+1):
    _s_old = _s.copy()
    for p in range(1, _2n1):
        i = indices[p]
        j = _j[p]
        if _s_old[p] == 1 and p%2==1:
            parent = (p-1) // 2
            k = (indices[parent] + _j[parent])//2
            if p %2 == 1:
                t[k] = _out[p]
            _out[parent] += _out[p] + _out[p+1]
            _s[parent] = 1
            _s[p] = 0
#print(_s)

16 5 63
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.6521086345453596, 0.22244854409583104, 0.22114381584364984, 0.5298141283918901, 0.15568316394733428, 0.7286351577448277, 0.7530795562502811, 0.09705636147277052, 0.015410940119010674, 0.5917942519060391, 0.3121686322301188, 0.16836890506349944, 0.9872248943168586, 0.6486223804126767, 0.4551809211411927, 0.8079910571898608, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
***********


In [1104]:
_out

[7.346731344671201,
 3.3599693622919444,
 3.9867619823792566,
 1.6255151228767306,
 1.7344542394152136,
 1.0877427293186681,
 2.8990192530605885,
 0.8745571786411906,
 0.75095794423554,
 0.884318321692162,
 0.8501359177230516,
 0.6072051920250497,
 0.48053753729361826,
 1.6358472747295352,
 1.2631719783310533,
 0.6521086345453596,
 0.22244854409583104,
 0.22114381584364984,
 0.5298141283918901,
 0.15568316394733428,
 0.7286351577448277,
 0.7530795562502811,
 0.09705636147277052,
 0.015410940119010674,
 0.5917942519060391,
 0.3121686322301188,
 0.16836890506349944,
 0.9872248943168586,
 0.6486223804126767,
 0.4551809211411927,
 0.8079910571898608,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [1105]:
np.sum(x)

7.346731344671201

In [33]:
%%cython --compile-args=-fopenmp --link-args=-fopenmp --force -a

from cython cimport boundscheck, wraparound
from libc.stdlib cimport malloc, free
cimport openmp

from cython.parallel import parallel, prange



cpdef mardas(double[:] x):
    cdef int i
    cdef int n = x.shape[0]
    with boundscheck(False), wraparound(False):
        with nogil:
            for i in xrange(n):
                x[i] = x[i] + 1
cpdef gamas(double[:] x):
    cdef int i
    cdef int n = x.shape[0]
    with boundscheck(False), wraparound(False):
        with nogil:
            for i in prange(n):
                x[i] = x[i] + 1
@wraparound(False)
@boundscheck(False)
cdef void abbas(double[:] x, int i, int j) nogil:
    cdef int p
    if j - i < 1000:
        for p in range(i, j+1):
            x[i] += 1
        return
    cdef int k = (i+j)//2
    for p in range(2):
        if p:
            abbas(x, i, k)
        else:
            abbas(x, k+1, j)
    
@wraparound(False)
@boundscheck(False)
cpdef abbase(double[:] x):
    cdef int n = x.shape[0]
    abbas(x, 0, n-1)

In [22]:
n = 10000000

x = np.random.rand(n)

In [23]:
y = x.copy()
%timeit mardas(y)

9.3 ms ± 7.66 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [29]:
y = x.copy()
%timeit gamas(y)

9.14 ms ± 35.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [27]:
y = x.copy()
%timeit abbase(y)

8.44 ms ± 7.76 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
y

array([       inf, 0.67398049, 0.49761939, ..., 0.48585404, 0.89744736,
       0.66002809])

In [1381]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
#x = np.random.rand(16)
n = len(x)
d = int(np.log2(n))
indices = [0 for _ in range(n)]
_j = [0 for _ in range(n)]
_s = np.array([0 for _ in range(n)])
_out = [0 for _ in range(n)]
indices[0] = 0
_j[0] = n-1
_s[0] = 1
for d in range(0, d+1):
    print(d)
    print(_s)
    _s_old = _s.copy()
    for p in range(n):
        i = indices[p]
        j = _j[p]
        if _s_old[p] > 0:
            if i == j:
                _out[p] = x[i]
            else:
                k = (indices[p] + _j[p])//2
                p_right = p+2**d
                #print(p, p_left, p_right)
                indices[p_right] = k+1
                _j[p_right] = j
                _s[p_right] = p+1
                indices[p] = i
                _j[p] = k
                _s[p] = p+1
                
#for d in reversed(range(0, d+1)):
#    print(_s)
#    _s_old = _s.copy()
#    for p in range(n):
#        i = indices[p]
#        j = _j[p]
#        if _s_old[p] == d:
#            _out[p] = 

0
[1 0 0 0 0 0 0 0 0 0 0]
1
[11 11  0  0  0  0  0  0  0  0  0]
2
[121 122 121 122   0   0   0   0   0   0   0]
3
[1331 1343 1333 1345 1331 1343 1333 1345    0    0    0]


In [1]:
import multiprocessing
# We must import this explicitly, it is not imported by the top-level
# multiprocessing module.
import multiprocessing.pool

In [2]:
class NoDaemonProcess(multiprocessing.Process):
    # make 'daemon' attribute always return False
    def _get_daemon(self):
        return False
    def _set_daemon(self, value):
        pass
    daemon = property(_get_daemon, _set_daemon)

# We sub-class multiprocessing.pool.Pool instead of multiprocessing.Pool
# because the latter is only a wrapper function, not a proper class.
class MyPool(multiprocessing.pool.Pool):
    Process = NoDaemonProcess

In [42]:
import queue
for i in range(10):
    q.put(i)
def fun(args):
    x, i, j = args
    if i == j:
        return x[i]
    else:
        k = (i+j)//2
        if not q.empty():
            _id = q.get()
            with MyPool(2) as pool:
                a = pool.map(fun, [(x, i, k)])
                b = fun((x,k+1,j))
            q.put(_id)
            return a[0] + b
        else:
            a = fun((x,i,k))
            b = fun((x,k+1,j))
            return a[0]+b

In [43]:
n = 30
fun((list(range(0, n)), 0, n-1))

435

In [41]:
import time
def fun(args):
    time.sleep(2)
    return 2
with MyPool(2) as pool:
    a = pool.map(fun, [(None)])
    print('mardas')
print(a)

mardas
[2]


KeyboardInterrupt: 