In [1]:
%load_ext autoreload
%autoreload 2
%reset -f
from imports import *
from additive.utility import dfe
from sh import wget

In [8]:
links = {
    # "V19_T1_Left(Bottom)_500X_3D_2.csv": "https://auburn.box.com/shared/static/0iy6dopmmq8c8owpkjc1rddn48czeam1.csv",
    # "V19_T1_Right(Top)_500X_3D_2.csv": "https://auburn.box.com/shared/static/i39htg5ku0wxphc9l6yebe63g7qatsd9.csv",
    # "V19_T2_Left(Bottom)_500X_3D_2.csv": "https://auburn.box.com/shared/static/856x1lsjqr0ldl7dlesv1rsyzdw84b3x.csv",
    # "V19_T2_Right(Top)_500X_3D_2.csv": "https://auburn.box.com/shared/static/6kykrfjuwiounoduupk4yebuq2ah4k80.csv"
    # "Polished_V01_T1_Right(Top)_500X_3D.csv": "https://auburn.box.com/shared/static/3m7cewgbcdd3hd6ahujpymng7xvlsmwx.csv",
    # "Polished_V01_T1_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/tmhzb05tyv3vpaqqlil9k2lndmhrbb0m.csv",
    # "Polished_V01_T2_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/h8d99m1bbtt7f6jzxzpy2lmhx1kfgkru.csv",
    # "V02_T1_Right(Top)_500X_3D.csv": "https://auburn.box.com/shared/static/4zq76ajxrfkd6o4cp807gmz9ogyi9u76.csv",
    # "V02_T1_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/agferqljomez0a9mrlh7030ptfxrmu9o.csv",
    "V02_T2_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/mlvxhct47mgsvy6gea28nk3ay3fmj2pl.csv",
    "V02_T2_Right(Top)_500X_3D.csv": "https://auburn.box.com/shared/static/z9hfsjbe63yw2okhqu737lwapnnhv95f.csv",
    # "V03_T1_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/rp15w7pa24jgxt3s0ze0tixgctrlk2vz.csv",
    # "V03_T1_Right(Top)_500X_3D.csv": "https://auburn.box.com/shared/static/qs7u4jv63ref6rcyja8gx74b8zi6v5jv.csv",
    # "V03_T2_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/i7995tlkgmo1lcopeqd8rnk0qqq155q1.csv",
     "V03_T2_Right(Top)_500X_3D.csv": "https://auburn.box.com/shared/static/z4ul74q4x9cptb5m7v0413jtz4bqnnku.csv",
    # "V04_T2_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/4gzvxn7r6dj53t6an0kybrwtjd0uq39f.csv",
    # "V04_T2_Right(Top)_500X_3D.csv": "https://auburn.box.com/shared/static/90q68vjl8w8iyr66wxnwpp9t505b3i29.csv",
    # "V04_T1_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/f0q0qkrqkwi1a62xkx3o9vkuraz197bf.csv",
    # "V04_T1_Right(Top)_500X_3D.csv": "https://auburn.box.com/shared/static/cevxt9vaigyd9vlv6w1fe340hdq2ofse.csv",
    # "V05_T2_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/gx6mowqb3m2ytn1l2v83xunz9l8pkpbo.csv",
    # "V05_T2_Right(Top)_500X_3D.csv": "https://auburn.box.com/shared/static/hlbeiklias8so016e0rvns6318htt10m.csv",
    # "V05_T1_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/ze0xsi0d6ad33m2z7cpme6n0m4j82piw.csv",
    # "V05_T1_Right(Top)_500X_3D.csv": "https://auburn.box.com/shared/static/so2y5u4d2vyoeuqqohq67qs7gsienlvd.csv",
    # "V06_T1_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/wibxwxvz1r9p02bakxb3i186nmmntrdn.csv",
    # "V06_T1_Right(Top)_500X_3D.csv": "https://auburn.box.com/shared/static/5p9r6gntla0wg46ov8vawoxhlqy2cgb4.csv",
    # "V06_T2_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/bumm16b88utg108wu57r732120t6pima.csv",
    # "V06_T2_Right(Top)_500X_3D.csv": "https://auburn.box.com/shared/static/xarwsorylyxo9njcf77u2sffecft4l4j.csv",
    # "V07_T1_Left(Bottom)_500X_3D.csv": "https://auburn.box.com/shared/static/e13wkyvftv9tm1mp4meaeyv1993vkc52.csv",
}

In [9]:
from additive.utility import download_from_dict

In [10]:
download_from_dict(links, "/home/ben_rasoolov/additive_project/data/original_images/")

([, , ],)


In [14]:
!du -hs /home/ben_rasoolov/additive_project/data/original_images/*csv

2.2G	/home/ben_rasoolov/additive_project/data/original_images/V02_T1_Left(Bottom)_500X_3D.csv
2.2G	/home/ben_rasoolov/additive_project/data/original_images/V02_T1_Right(Top)_500X_3D.csv
2.1G	/home/ben_rasoolov/additive_project/data/original_images/V02_T2_Left(Bottom)_500X_3D.csv
2.1G	/home/ben_rasoolov/additive_project/data/original_images/V02_T2_Right(Top)_500X_3D.csv
2.2G	/home/ben_rasoolov/additive_project/data/original_images/V03_T1_Left(Bottom)_500X_3D.csv
2.2G	/home/ben_rasoolov/additive_project/data/original_images/V03_T1_Right(Top)_500X_3D.csv
2.2G	/home/ben_rasoolov/additive_project/data/original_images/V03_T2_Left(Bottom)_500X_3D.csv
2.2G	/home/ben_rasoolov/additive_project/data/original_images/V03_T2_Right(Top)_500X_3D.csv
2.2G	/home/ben_rasoolov/additive_project/data/original_images/V04_T1_Left(Bottom)_500X_3D.csv
2.2G	/home/ben_rasoolov/additive_project/data/original_images/V04_T1_Right(Top)_500X_3D.csv
2.2G	/home/ben_rasoolov/additive_project/data/original_images/V04_T2_L

In [11]:
csv_files = glob.glob("/home/ben_rasoolov/additive_project/data/original_images/*csv")

In [13]:
def proces_csv_files(file):
    print(file)
    d, f, e = dfe(file)
    x = pd.read_csv(file, header=None)
    joblib.dump(x.values.astype('float32'), d+f+".pd")

with Pool(4) as p:
    p.map(proces_csv_files, csv_files)

/home/ben_rasoolov/additive_project/data/original_images/V06_T2_Left(Bottom)_500X_3D.csv
/home/ben_rasoolov/additive_project/data/original_images/V04_T2_Right(Top)_500X_3D.csv/home/ben_rasoolov/additive_project/data/original_images/V02_T2_Right(Top)_500X_3D.csv

/home/ben_rasoolov/additive_project/data/original_images/V02_T1_Right(Top)_500X_3D.csv
/home/ben_rasoolov/additive_project/data/original_images/V04_T1_Right(Top)_500X_3D.csv
/home/ben_rasoolov/additive_project/data/original_images/V06_T2_Right(Top)_500X_3D.csv
/home/ben_rasoolov/additive_project/data/original_images/V03_T1_Left(Bottom)_500X_3D.csv
/home/ben_rasoolov/additive_project/data/original_images/V03_T2_Left(Bottom)_500X_3D.csv
/home/ben_rasoolov/additive_project/data/original_images/V06_T1_Left(Bottom)_500X_3D.csv
/home/ben_rasoolov/additive_project/data/original_images/V05_T1_Right(Top)_500X_3D.csv
/home/ben_rasoolov/additive_project/data/original_images/V04_T2_Left(Bottom)_500X_3D.csv
/home/ben_rasoolov/additive_proje

In [15]:
ls /home/ben_rasoolov/additive_project/data/original_images/

'V02_T1_Left(Bottom)_500X_3D.csv'  'V04_T2_Left(Bottom)_500X_3D.csv'
'V02_T1_Left(Bottom)_500X_3D.pd'   'V04_T2_Left(Bottom)_500X_3D.pd'
'V02_T1_Right(Top)_500X_3D.csv'    'V04_T2_Right(Top)_500X_3D.csv'
'V02_T1_Right(Top)_500X_3D.pd'     'V04_T2_Right(Top)_500X_3D.pd'
'V02_T2_Left(Bottom)_500X_3D.csv'  'V05_T1_Left(Bottom)_500X_3D.csv'
'V02_T2_Left(Bottom)_500X_3D.pd'   'V05_T1_Left(Bottom)_500X_3D.pd'
'V02_T2_Right(Top)_500X_3D.csv'    'V05_T1_Right(Top)_500X_3D.csv'
'V02_T2_Right(Top)_500X_3D.pd'     'V05_T1_Right(Top)_500X_3D.pd'
'V03_T1_Left(Bottom)_500X_3D.csv'  'V05_T2_Left(Bottom)_500X_3D.csv'
'V03_T1_Left(Bottom)_500X_3D.pd'   'V05_T2_Left(Bottom)_500X_3D.pd'
'V03_T1_Right(Top)_500X_3D.csv'    'V05_T2_Right(Top)_500X_3D.csv'
'V03_T1_Right(Top)_500X_3D.pd'     'V05_T2_Right(Top)_500X_3D.pd'
'V03_T2_Left(Bottom)_500X_3D.csv'  'V06_T1_Left(Bottom)_500X_3D.csv'
'V03_T2_Left(Bottom)_500X_3D.pd'   'V06_T1_Left(Bottom)_500X_3D.pd'
'V03_T2_Right(Top)_500X_3D.csv'    'V06_T1_Right(Top)

In [16]:
from additive.preprocessing import gkern2d
from scipy.ndimage import zoom, convolve
def get_all_stats(files, n_processes=4):
    s = np.array([2.330435, 2.33016])
    M = 31
    _ = gkern2d(M, 5)
    k3 = _ / _.sum()
    original_images = bag.from_sequence(files).map(joblib.load)
    resized_images   = original_images.map(zoom, zoom=1/s)
    smoothed_images = resized_images.map(convolve, weights=k3)
    from multiprocessing import Pool
    with dask.config.set(pool=Pool(min(n_processes, len(files)))):
        all_stats = smoothed_images.compute()
    return all_stats

In [17]:
raw_images = glob.glob("/home/ben_rasoolov/additive_project/data/original_images/*pd")

In [ ]:
images = get_all_stats(raw_images, n_processes=8)

In [20]:
len(images)

20

In [26]:
from additive.utility import save_list_to_files

In [32]:
save_list_to_files(images, raw_images, "/home/ben_rasoolov/additive_project/data/experiment_03/", 
                   ".info", overwrite='backup')

File /home/ben_rasoolov/additive_project/data/experiment_03//V06_T2_Left(Bottom)_500X_3D.info exists. Moving it to old_out_path
File /home/ben_rasoolov/additive_project/data/experiment_03//V06_T2_Right(Top)_500X_3D.info exists. Moving it to old_out_path
File /home/ben_rasoolov/additive_project/data/experiment_03//V04_T2_Left(Bottom)_500X_3D.info exists. Moving it to old_out_path
File /home/ben_rasoolov/additive_project/data/experiment_03//V03_T1_Left(Bottom)_500X_3D.info exists. Moving it to old_out_path
File /home/ben_rasoolov/additive_project/data/experiment_03//V02_T2_Left(Bottom)_500X_3D.info exists. Moving it to old_out_path
File /home/ben_rasoolov/additive_project/data/experiment_03//V04_T1_Left(Bottom)_500X_3D.info exists. Moving it to old_out_path
File /home/ben_rasoolov/additive_project/data/experiment_03//V04_T2_Right(Top)_500X_3D.info exists. Moving it to old_out_path
File /home/ben_rasoolov/additive_project/data/experiment_03//V02_T1_Right(Top)_500X_3D.info exists. Moving i

In [1]:
%load_ext autoreload
%autoreload 2
%reset -f
from imports import *

In [2]:
files = glob.glob("/home/ben_rasoolov/additive_project/data/experiment_03/*info")

In [16]:
from additive.feature_functions import feature_functions_functions as fff
from additive.preprocessing import image_from_info_file, process_image

In [17]:
@delayed
def get_all_global_stats(file, fff):
    print(file)
    image = image_from_info_file(file)
    processed_image = process_image(image)
    return {k: v(processed_image) for k, v in fff.items()}

In [18]:
out = [get_all_global_stats(file, fff) for file in files]

In [19]:
all_stats = compute(out)[0]

/home/ben_rasoolov/additive_project/data/experiment_03/V19_T2_Right(Top)_500X_3D.info/home/ben_rasoolov/additive_project/data/experiment_03/Polished_V13_T2_Right(Top)_500X_3D.info/home/ben_rasoolov/additive_project/data/experiment_03/V19_T1_Right(Top)_500X_3D.info/home/ben_rasoolov/additive_project/data/experiment_03/V11_T2_Right(Top)_500X_3D.info/home/ben_rasoolov/additive_project/data/experiment_03/V19_T2_Left(Bottom)_500X_3D.info/home/ben_rasoolov/additive_project/data/experiment_03/V04_T1_R_3d.info/home/ben_rasoolov/additive_project/data/experiment_03/V05_T1_R_3d.info/home/ben_rasoolov/additive_project/data/experiment_03/Polished_V01_T2_Left(Bottom)_500X_3D.info

/home/ben_rasoolov/additive_project/data/experiment_03/V10_T2_Left(Bottom)_500X_3D.info/home/ben_rasoolov/additive_project/data/experiment_03/V02_T1_Right(Top)_500X_3D.info
/home/ben_rasoolov/additive_project/data/experiment_03/V05_T1_L_3d.info




/home/ben_rasoolov/additive_project/data/experiment_03/Polished_V13_T2_Left

[ 1.08968709e-02 -5.77584101e-04 -1.48378799e-06  1.86607544e-07]
[ 1.52891655e-02  8.10850422e-04 -2.10872578e-06 -3.05354665e-07]
/home/ben_rasoolov/additive_project/data/experiment_03/V18_T1_Right(Top)_500X_3D.info
/home/ben_rasoolov/additive_project/data/experiment_03/Polished_V15_T2_Left(Bottom)_500X_3D.info
/home/ben_rasoolov/additive_project/data/experiment_03/V04_T1_Left(Bottom)_500X_3D.info
/home/ben_rasoolov/additive_project/data/experiment_03/Polished_V03_T2_Right(Top)_500X_3D.info
[ 2.26234863e-02  1.96506226e-03 -3.22536561e-06 -2.69058828e-08]
/home/ben_rasoolov/additive_project/data/experiment_03/V04_T2_Right(Top)_500X_3D.info
[ 1.42750788e-02 -1.38957065e-04 -1.40723491e-06  1.76694836e-07]
[ 8.05291070e-03  2.48555232e-03 -1.13633469e-06 -6.25720388e-08]
[ 1.90093786e-02  5.44401041e-04 -2.47391398e-06  2.33253759e-07]
/home/ben_rasoolov/additive_project/data/experiment_03/V14_T1_Right(Top)_500X_3D.info
/home/ben_rasoolov/additive_project/data/experiment_03/V01_T2_Righ

[ 9.80100457e-03 -3.02482360e-03 -1.36412575e-06  8.23705244e-08]
[ 1.62773294e-02  1.30026136e-03 -2.25104641e-06  1.18275790e-07]
[ 6.40497117e-03 -2.07893455e-03 -1.09350877e-06  2.16186740e-07]
/home/ben_rasoolov/additive_project/data/experiment_03/V08_T2_Right(Top)_500X_3D.info
/home/ben_rasoolov/additive_project/data/experiment_03/Polished_V13_T1_Right(Top)_500X_3D.info
/home/ben_rasoolov/additive_project/data/experiment_03/V06_T2_R_3d.info
/home/ben_rasoolov/additive_project/data/experiment_03/V05_T1_Left(Bottom)_500X_3D.info
/home/ben_rasoolov/additive_project/data/experiment_03/V17_T1_Left(Bottom)_500X_3D.info
/home/ben_rasoolov/additive_project/data/experiment_03/V08_T1_Right(Top)_500X_3D.info
[ 7.39527304e-03 -3.32776008e-03 -1.24969680e-06  2.15907352e-07]
[-5.14047172e-04 -2.35033783e-03  6.83046830e-07  1.68691441e-07]
[ 2.73739662e-02 -2.21513732e-03 -3.15372677e-06  5.61698400e-07]
[ 9.61360209e-03  5.95204295e-05 -1.48892858e-06 -6.47023423e-08]
[ 3.07133024e-02 -5.227

In [14]:
from additive.utility import get_file_info
get_file_info(pd.DataFrame(all_stats).assign(file=files), 'file')\
    #.to_csv("/home/ben_rasoolov/additive_project/data/paper/data/global_stats_no_transform_v02.csv")